[package]
name = "ink_lang2_macro"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

license = "MIT/Apache-2.0"
readme = "README.md"

description = "[ink!] Rust based eDSL for writing smart contracts for Substrate"
keywords = ["wasm", "parity", "webassembly", "blockchain", "edsl"]
categories = ["no-std", "embedded"]

include = ["Cargo.toml", "src/**/*.rs", "README.md", "LICENSE"]

[dependencies]
ink_utils = { path = "../../utils/", default-features = false }

scale = { package = "parity-scale-codec", version = "1.1", default-features = false, features = ["derive"] }
quote = "1"
syn = { version = "1.0", features = ["parsing", "full", "extra-traits"] }
proc-macro2 = "1.0"
heck = "0.3"
itertools = { version = "0.8.1", default-features = false }
either = { version = "1.5", default-features = false }
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde_json = "1.0"
derive_more = { version = "0.99.1", default-features = false, features = ["from"] }
regex = "1.3"

[dev-dependencies]
ink_abi = { path = "../../abi/" }
ink_core = { path = "../../core/" }
ink_lang2 = { path = "..", default-features = false, features = ["ink-generate-abi"] }
type-metadata = { git = "https://github.com/type-metadata/type-metadata.git", default-features = false, features = ["derive"] }

trybuild = "1.0"
pretty_assertions = "0.6.1"

[lib]
name = "ink_lang2_macro"
proc-macro = true

[features]
default = ["test-env"]
std = [
    "ink_utils/std",
    "scale/std",
    "itertools/use_std",
    "either/use_std",
    "serde/std",
]
test-env = [
    "std",
]
ink-generate-abi = [
    "std",
]
