language: rust
cache: cargo
dist: trusty
sudo: true

rust:
  # - stable
  # - beta
  - nightly
  - nightly-2019-08-13

matrix:
  allow_failures:
    - rust: nightly
    # - rust: stable
    # - rust: beta

env:
  global:
  - RUSTFLAGS="-C link-dead-code"

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - libiberty-dev
      - g++
      - cmake
      - zlib1g-dev

install:
  # Print rustc and cargo versions
  - rustc -vV
  - cargo -vV
  - bash --version
  # Install cargo-kcov Cargo plugin
  - cargo install --force cargo-kcov
  - cargo kcov -vV
  # Install kcov binary
  - wget https://github.com/SimonKagstrom/kcov/archive/v36.tar.gz
  - tar xzf v36.tar.gz
  - pushd kcov-36
  - mkdir build
  - pushd build
  - cmake ..
  - make
  - sudo make install # Puts kcov in the default location usually /usr/local/bin/kcov
  - kcov --version
  - popd
  - popd
  # Export cargo binaries, python and misc settings
  - export PATH=$HOME/.local/bin:$HOME/.cargo/bin:$HOME/Library/Python/2.7/bin:$PATH
  # Print current work directory state as directions.
  - ls -lah

before_script:
  - rustup component add clippy rustfmt
  - rustup target add wasm32-unknown-unknown

script:
- |
  ./scripts/check-workspace.sh
  check_workspace=$?

  if [ $check_workspace -eq 0 ]
  then
    # Execute and upload kcov results
    cargo kcov --verbose --coveralls --all --no-clean-rebuild
    kcov=$?
    bash <(curl -s https://codecov.io/bash)
  fi

  ./scripts/check-examples.sh
  check_examples=$?

  if [ $check_examples -eq 0 ] && [ $check_workspace -eq 0 ]
  then
    echo "All checks have passed!"
    exit 0
  else
    echo "Some checks have not passed!"
    exit 1
  fi
