status = [
    "ci/gitlab/gitlab.parity.io",
    "continuous-integration/gitlab-build-wasm",
    "continuous-integration/gitlab-check-std",
    "continuous-integration/gitlab-check-wasm",
    "continuous-integration/gitlab-clippy-std",
    "continuous-integration/gitlab-clippy-wasm",
    "continuous-integration/gitlab-examples-clippy-std",
    "continuous-integration/gitlab-examples-clippy-wasm",
    "continuous-integration/gitlab-examples-contract-build",
    "continuous-integration/gitlab-examples-fmt",
    "continuous-integration/gitlab-examples-generate-metadata",
    "continuous-integration/gitlab-examples-test",
    "continuous-integration/gitlab-fmt",
    "continuous-integration/gitlab-publish-docs",
    "continuous-integration/gitlab-test"
]
# The default is one hour.
timeout_sec = 600
use_squash_merge = true
required_approvals = 1
