status = [
<<<<<<< HEAD
    "ci/gitlab/gitlab.parity.io"
=======
  "ci/gitlab/gitlab-check-std",
  "ci/gitlab/gitlab-build-std",
  "ci/gitlab/gitlab-examples-test",
  "continuous-integration/gitlab-check-std",
  "continuous-integration/gitlab-check-wasm",
  "continuous-integration/gitlab-test",
  "continuous-integration/gitlab-build-std ",
  "continuous-integration/gitlab-build-wasm",
  "continuous-integration/gitlab-clippy-std",
  "continuous-integration/gitlab-clippy-wasm",
  "continuous-integration/gitlab-fmt",
  # "ci/gitlab/gitlab.parity.io",
  # "continuous-integration/gitlab-cargo-audit",
  # "continuous-integration/gitlab-check_warnings",
  # "continuous-integration/gitlab-test-linux-stable",
  "ci/gitlab/master ",
  "ci/gitlab/gitlab.parity.io"
>>>>>>> borsconf to track GL jobs in two ways
]
# The default is one hour (3600 sec).
timeout_sec = 1800
use_squash_merge = true
required_approvals = 1
