status = [
  "ci/gitlab/gitlab.parity.io"
  # "continuous-integration/gitlab-check-std"
  # "continuous-integration/gitlab-build-std",
  # "continuous-integration/gitlab-examples-test"
]
# WORKS 'ci/gitlab/%']
# Uncomment this to use a two hour timeout.
# The default is one hour.
timeout_sec = 600

# Do not allow pull requests with these labels to be merged.
block_labels = [
    "status: question",
    "status: blocked",
    "status: discussing",
    "status: in progress",
    "status: needs triage"
]

# "ci/gitlab/gitlab-check-std",
#   "ci/gitlab/gitlab-build-std",
#   "ci/gitlab/gitlab-examples-test",
# "continuous-integration/gitlab-check-wasm",
#   "continuous-integration/gitlab-test",
#   "continuous-integration/gitlab-build-std ",
#   "continuous-integration/gitlab-build-wasm",
#   "continuous-integration/gitlab-clippy-std",
#   "continuous-integration/gitlab-clippy-wasm",
#   "continuous-integration/gitlab-fmt",
#   # "ci/gitlab/gitlab.parity.io",
#   # "continuous-integration/gitlab-cargo-audit",
#   # "continuous-integration/gitlab-check_warnings",
#   # "continuous-integration/gitlab-test-linux-stable",
#   "ci/gitlab/master ",
#   "ci/gitlab/gitlab.parity.io"
