[workspace]
members = [
    "crates/metadata",
    "crates/alloc",
    "crates/core",
    "crates/core/derive",
    "crates/lang",
    "crates/lang/macro",
    "crates/lang/ir",
    "crates/lang/codegen",
    "crates/prelude",
    "crates/primitives",
]
exclude = [
    "examples/",
]

[profile.release]
panic = "abort"
lto = true
