[workspace]
members = [
    "crates/metadata",
    "crates/allocator",
    "crates/lang",
    "crates/lang/macro",
    "crates/lang/ir",
    "crates/lang/codegen",
    "crates/prelude",
    "crates/primitives",
    "crates/env",
    "crates/storage",
    "crates/storage/derive",
]
exclude = [
    "examples/",
]

[profile.release]
panic = "abort"
lto = true

# TODO remove, only needed until change gets released
[patch.crates-io]
# parity-scale-codec = { path = "../parity-scale-codec" }
parity-scale-codec = { git = "https://github.com/austinabell/parity-scale-codec", rev = "1feb094862530eebdce56ae37bdddee525fc64a1" }