[workspace]

members = [
    "utils",
    "core",
    "model",
    "lang",
    "cli",
]
exclude = [
    "examples/",
]

[profile.release]
panic = "abort"
lto = true

[patch.crates-io]
jsonrpc-derive = { git = "https://github.com/dvc94ch/jsonrpc", branch = "dvc-client-pubsub", package = "jsonrpc-derive" }
jsonrpc-core-client = { git = "https://github.com/dvc94ch/jsonrpc", branch = "dvc-client-pubsub", package = "jsonrpc-core-client", features = ["http", "ws"] }
jsonrpc-core = { git = "https://github.com/dvc94ch/jsonrpc", branch = "dvc-client-pubsub", package = "jsonrpc-core" }
jsonrpc-pubsub = { git = "https://github.com/dvc94ch/jsonrpc", branch = "dvc-client-pubsub", package = "jsonrpc-pubsub" }
