[workspace]

members = [
    "utils",
    "core",
    "model",
    "lang",
    "cli",
    "types/node_runtime",
    "types/default"
]
exclude = [
    "examples/",
]

[profile.release]
panic = "abort"
lto = true
