[package]
name = "cargo-contract"
version = "0.1.1"
authors = ["Parity Technologies <admin@parity.io>"]
build = "build.rs"
edition = "2018"

license = "GPL-3.0"
readme = "README.md"

description = "Setup and deployment tool for developing Wasm based smart contracts via ink!"
keywords = ["wasm", "parity", "webassembly", "blockchain", "edsl"]
categories = ["cli", "tool"]

include = ["/Cargo.toml", "src/**/*.rs", "/README.md", "/LICENSE"]

[dependencies]
env_logger = "0.6"
derive_more = "0.14.0"
structopt = "0.2.15"
itertools = "0.8"
log = "0.4"
heck = "0.3"
futures = "0.1.28"
jsonrpc-core-client = { version = "13.0", features = ["ws"] }
toml = "0.5"
zip = { version = "0.5", default-features = false }
node-runtime = { git = "https://github.com/paritytech/substrate/", package = "node-runtime", features = ["std"] }
runtime_primitives = { git = "https://github.com/paritytech/substrate/", package = "sr-primitives" }
serde = { version = "1.0", features = ["derive"] }
srml-contracts = { git = "https://github.com/paritytech/substrate/", package = "srml-contracts", features = ["core"] }
srml-balances = { git = "https://github.com/paritytech/substrate/", package = "srml-balances" }
srml-system = { git = "https://github.com/paritytech/substrate/", package = "srml-system" }
substrate-primitives = { git = "https://github.com/paritytech/substrate/", package = "substrate-primitives" }
subxt = { git = "https://github.com/paritytech/substrate-subxt/", branch = "xt-submit-and-watch", package = "substrate-subxt" }
tokio = "0.1.21"
url = "1.7"

[dev-dependencies]
wabt = "0.9.0"

[build-dependencies]
zip = { version = "0.5", default-features = false }
walkdir = "1.0"
