[package]
name = "ink_core"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

license = "GPL-3.0"
readme = "README.md"

repository = "https://github.com/paritytech/ink"
documentation = "https://github.com/paritytech/ink/wiki"
homepage = "https://www.parity.io/"

description = "[ink!] Rust based eDSL for writing smart contracts for Substrate"
keywords = ["wasm", "parity", "webassembly", "blockchain", "edsl"]
categories = ["no-std", "embedded"]

include = ["/Cargo.toml", "src/**/*.rs", "/README.md", "/LICENSE"]

[dependencies]
ink_alloc = { path = "../alloc/" }
ink_utils = { path = "../utils/" }
parity-codec = { version = "4.1.1", default-features = false, features = ["derive", "full"] }

[dev-dependencies]
node-runtime = { git = "https://github.com/paritytech/substrate/", package = "node-runtime", default_features = false }
srml-indices = { git = "https://github.com/paritytech/substrate/", package = "srml-indices", default_features = false }

[features]
default = []
test-env = ["std"]
std = [
    "ink_alloc/std",
    "ink_utils/std",
    "node-runtime/std",
    "srml-indices/std",
]
