[package]
name = "ink_core"
version = "0.1.0"
authors = ["Robin Freyler <robin@parity.io>", "Parity Technologies <admin@parity.io>"]
edition = "2018"

license = "GPL-3.0"
readme = "README.md"

# repository = "https://github.com/robbepop/substrate-contract"
# homepage = "https://github.com/robbepop/substrate-contract"
# documentation = "https://robbepop.github.io/pwasm-abi/substrate-contract/"

description = "[pDSL: Parity eDSL] Rust based eDSL for writing smart contracts for Substrate"
keywords = ["wasm", "parity", "webassembly", "blockchain", "edsl"]
categories = ["no-std", "embedded"]

include = ["/Cargo.toml", "src/**/*.rs", "/README.md", "/LICENSE"]

[dependencies]
ink_utils = { path = "../utils/" }
parity-codec = { version = "3.2", default-features = false, features = ["derive", "full"] }
log = "0.4"
wee_alloc = { version = "0.4", default-features = false }
node-runtime = { git = "https://github.com/paritytech/substrate/", branch = "v1.0", package = "node-runtime", default-features = false }
# FIXME: remove these direct dependencies if possible to access the trait associated types
srml-system = { git = "https://github.com/paritytech/substrate/", branch = "v1.0", package = "srml-system", default-features = false }
srml-balances = { git = "https://github.com/paritytech/substrate/", branch = "v1.0", package = "srml-balances", default-features = false }
# FIXME: remove this restriction once https://github.com/paritytech/substrate/pull/2327 backported to v1.0
syn = { version = ">= 0.15.30, < 0.15.32", features = ["full"] } # newest version 0.15.32 breaks srml-support

[features]
default = []
test-env = ["std"]
std = [
	"node-runtime/std",
	"srml-system/std",
    "srml-balances/std",
]
