[package]
name = "erc20"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
ink_core = { path = "../../../core", default-features = false }
parity-codec = { version = "4.1", default-features = false, features = ["derive"] }

[lib]
name = "erc20"
crate-type = ["cdylib"]

[features]
default = ["std"]
std = [
	"ink_core/std",
	"parity-codec/std",
]
test-env = [
	"std",
	"ink_core/test-env",
]

[profile.release]
panic = "abort"
lto = true
opt-level = "z"
