[package]
name = "subpeep"
version = "0.1.0"
authors = ["Robin Freyler <robin@parity.io>", "Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
pdsl_core = { path = "../../pdsl_core" }

parity-codec = { version = "2.0.4", default-features = false }
parity-codec-derive = { version = "2.0.4", default-features = false }
wee_alloc = "0.4"

lazy_static = "1.2"

[lib]
name = "subpeep"

[features]
default = []
test-env = ["pdsl_core/test-env"]
