[package]
name = "adder"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
ink_abi = { path = "../../../../abi", default-features = false, features = ["derive"], optional = true }
ink_core = { path = "../../../../core", default-features = false }
ink_lang2 = { path = "../../../../lang2", default-features = false }

scale = { package = "parity-scale-codec", version = "1.0", default-features = false, features = ["derive"] }
type-metadata = { git = "https://github.com/type-metadata/type-metadata.git", default-features = false, features = ["derive"], optional = true }

accumulator = { path = "../accumulator", default-features = false, features = ["ink-as-dependency"] }

[lib]
name = "adder"
path = "lib.rs"
crate-type = [
	# Used for normal contract Wasm blobs.
	"cdylib",
	# Used for ABI generation.
	"rlib",
]

[features]
default = ["test-env"]
std = [
    "ink_abi/std",
    "ink_core/std",
    "ink_lang2/std",
    "scale/std",
    "type-metadata/std",

    "accumulator/std",
]
test-env = [
	"std",
    "ink_core/test-env",
    "ink_lang2/test-env",
]
ink-generate-abi = [
    "std",
    "ink_abi",
    "type-metadata",
    "ink_core/ink-generate-abi",
    "ink_lang2/ink-generate-abi",

    "accumulator/ink-generate-abi",
]
ink-as-dependency = []
