[package]
name = "runtime"
version = "0.1.0"
authors = ["admin@parity.io"]
edition = "2018"

[dependencies]
pdsl_core = { path = "../../../core" }
pdsl_model = { path = "../../../model" }
pdsl_lang = { path = "../../../lang" }
parity-codec = { version = "3.2", default-features = false, features = ["derive"] }

[lib]
name = "runtime"
crate-type = ["cdylib"]

[features]
default = []
test-env = [
    "pdsl_core/test-env",
    "pdsl_model/test-env",
    "pdsl_lang/test-env",
]
generate-api-description = [
    "pdsl_lang/generate-api-description"
]

[profile.release]
panic = "abort"
lto = true
opt-level = "z"
