[package]
name = "delegator"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
ink_primitives = { path = "../../primitives", default-features = false }
ink_abi = { path = "../../abi", default-features = false, features = ["derive"], optional = true }
ink_core = { path = "../../core", default-features = false }
ink_lang = { path = "../../lang", default-features = false }

scale = { package = "parity-scale-codec", version = "1.2", default-features = false, features = ["derive"] }
type-metadata = { git = "https://github.com/type-metadata/type-metadata.git", default-features = false, features = ["derive"], optional = true }

adder = { path = "adder", default-features = false, features = ["ink-as-dependency"] }
subber = { path = "subber", default-features = false, features = ["ink-as-dependency"] }
accumulator = { path = "accumulator", default-features = false, features = ["ink-as-dependency"] }

[lib]
name = "delegator"
path = "lib.rs"
crate-type = [
	# Used for normal contract Wasm blobs.
	"cdylib",
	# Used for ABI generation.
	"rlib",
]

[features]
default = ["test-env"]
std = [
    "ink_primitives/std",
    "ink_abi/std",
    "ink_core/std",
    "ink_lang/std",
    "scale/std",
    "type-metadata/std",

    "adder/std",
    "subber/std",
    "accumulator/std",
]
test-env = [
	"std",
    "ink_lang/test-env",
    "type-metadata/std",

    "adder/test-env",
    "subber/test-env",
    "accumulator/test-env",
]
ink-generate-abi = [
    "std",
    "ink_abi",
    "type-metadata",
    "ink_core/ink-generate-abi",

    "adder/ink-generate-abi",
    "subber/ink-generate-abi",
    "accumulator/ink-generate-abi",
]
ink-as-dependency = []

[profile.release]
panic = "abort"
lto = true
opt-level = "z"
overflow-checks = true

[workspace]
members = [
	".ink/abi_gen",
    "accumulator",
    "adder",
    "subber",
]
exclude = [
	".ink"
]
